# Site settings
title: Grimoire
email: me@arrdem.com
description: "Community documentation of Clojure"
baseurl: "http://www.arrdem.com/grimoire/"
url: "http://www.arrdem.com/grimoire/"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
